project_id = "iwqcltmeniotzbowbxzg"

[functions.generate-html]
verify_jwt = false

[functions.totem-config]
verify_jwt = false

[functions.totem-heartbeat]
verify_jwt = false

[functions.totem-register]
verify_jwt = false

[functions.totem-poll-command]
verify_jwt = false

[functions.totem-command-report]
verify_jwt = false

[functions.totem-chat]
verify_jwt = false

[functions.ai-config]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.form-submit]
verify_jwt = false
