// Pre-defined Craft.js serialized templates for the Page Builder

export interface CraftTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: 'totem' | 'info' | 'menu' | 'promo';
  json: string;
}

// Helper to generate unique IDs
const uid = (prefix: string, idx: number) => `${prefix}_${idx}`;

export const CRAFT_TEMPLATES: CraftTemplate[] = [
  {
    id: 'welcome-avatar',
    name: 'Boas-vindas + Avatar',
    description: 'Avatar 3D com saudação e menu de ações rápidas',
    icon: '🧑‍💼',
    category: 'totem',
    json: JSON.stringify({
      ROOT: {
        type: { resolvedName: 'CanvasDropArea' },
        isCanvas: true,
        props: { bgColor: '#0f172a' },
        displayName: 'Canvas',
        custom: {},
        hidden: false,
        nodes: ['badge_1', 'avatar_1', 'spacer_1', 'menu_1'],
        linkedNodes: {},
      },
      badge_1: {
        type: { resolvedName: 'BadgeBlock' },
        isCanvas: false,
        props: { text: 'Bem-vindo!', emoji: '👋', bgColor: '#6366f1', textColor: '#ffffff', fontSize: 13, borderRadius: 999, variant: 'glass', align: 'center', pulse: false },
        displayName: 'Badge',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      avatar_1: {
        type: { resolvedName: 'AvatarBlock' },
        isCanvas: false,
        props: { enabled: true, avatarName: 'Assistente Virtual', height: 280, borderRadius: 16, bgColor: 'rgba(255,255,255,0.03)' },
        displayName: 'Avatar',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      spacer_1: {
        type: { resolvedName: 'SpacerBlock' },
        isCanvas: false,
        props: { height: 16 },
        displayName: 'Espaçador',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      menu_1: {
        type: { resolvedName: 'MenuBlock' },
        isCanvas: false,
        props: {
          title: 'Como posso ajudar?',
          titleIcon: '💬',
          items: [
            { id: '1', emoji: 'ℹ️', label: 'Informações', action: 'Me dê informações gerais', color: '#0ea5e9' },
            { id: '2', emoji: '📍', label: 'Localização', action: 'Onde estamos?', color: '#8b5cf6' },
            { id: '3', emoji: '📞', label: 'Contato', action: 'Como falar conosco?', color: '#10b981' },
            { id: '4', emoji: '⭐', label: 'Destaques', action: 'Quais são os destaques?', color: '#f59e0b' },
          ],
          layout: 'grid',
          columns: 2,
          bgColor: 'rgba(255,255,255,0.06)',
          bgOpacity: 1,
          bgBlur: 12,
          borderRadius: 16,
          gap: 8,
          padding: 16,
          titleColor: '#ffffff',
          titleFontSize: 14,
          itemBgColor: 'rgba(255,255,255,0.08)',
          itemTextColor: '#ffffff',
          itemFontSize: 13,
          itemBorderRadius: 12,
          showItemEmoji: true,
          collapsible: false,
          defaultOpen: true,
        },
        displayName: 'Menu',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
    }),
  },
  {
    id: 'info-kiosk',
    name: 'Kiosk Informativo',
    description: 'Card com informações, badges e botões de ação',
    icon: '📋',
    category: 'info',
    json: JSON.stringify({
      ROOT: {
        type: { resolvedName: 'CanvasDropArea' },
        isCanvas: true,
        props: { bgColor: '#0f172a' },
        displayName: 'Canvas',
        custom: {},
        hidden: false,
        nodes: ['icon_1', 'text_title', 'divider_1', 'card_1', 'spacer_2', 'btn_1'],
        linkedNodes: {},
      },
      icon_1: {
        type: { resolvedName: 'IconBlock' },
        isCanvas: false,
        props: { emoji: '🏢', size: 40, bgColor: 'rgba(59,130,246,0.2)', bgEnabled: true, bgSize: 72, bgBorderRadius: 20, borderColor: 'rgba(59,130,246,0.3)', borderWidth: 1, align: 'center', shadow: true },
        displayName: 'Ícone',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      text_title: {
        type: { resolvedName: 'TextBlock' },
        isCanvas: false,
        props: { text: 'Central de Informações', fontSize: 22, fontWeight: 'bold', color: '#ffffff', textAlign: 'center', padding: 8 },
        displayName: 'Texto',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      divider_1: {
        type: { resolvedName: 'DividerBlock' },
        isCanvas: false,
        props: { color: 'rgba(255,255,255,0.1)', thickness: 1, margin: 8, lineStyle: 'solid' },
        displayName: 'Divisor',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      card_1: {
        type: { resolvedName: 'CardBlock' },
        isCanvas: true,
        props: { title: 'Horários', subtitle: 'Funcionamento', bgColor: 'rgba(255,255,255,0.06)', bgBlur: 16, borderRadius: 16, borderColor: 'rgba(255,255,255,0.1)', padding: 20, headerIcon: '🕐', showHeader: true, elevation: 'md' },
        displayName: 'Card',
        custom: {},
        hidden: false,
        nodes: ['card_text_1', 'card_text_2'],
        linkedNodes: {},
        parent: 'ROOT',
      },
      card_text_1: {
        type: { resolvedName: 'TextBlock' },
        isCanvas: false,
        props: { text: 'Segunda a Sexta: 09h - 22h', fontSize: 14, fontWeight: 'normal', color: '#e2e8f0', textAlign: 'left', padding: 4 },
        displayName: 'Texto',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'card_1',
      },
      card_text_2: {
        type: { resolvedName: 'TextBlock' },
        isCanvas: false,
        props: { text: 'Sábado e Domingo: 10h - 20h', fontSize: 14, fontWeight: 'normal', color: '#e2e8f0', textAlign: 'left', padding: 4 },
        displayName: 'Texto',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'card_1',
      },
      spacer_2: {
        type: { resolvedName: 'SpacerBlock' },
        isCanvas: false,
        props: { height: 12 },
        displayName: 'Espaçador',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      btn_1: {
        type: { resolvedName: 'ButtonBlock' },
        isCanvas: false,
        props: { label: 'Falar com Atendente', bgColor: '#3b82f6', textColor: '#ffffff', fontSize: 15, borderRadius: 12, paddingX: 24, paddingY: 14, fullWidth: true, action: 'Quero falar com um atendente' },
        displayName: 'Botão',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
    }),
  },
  {
    id: 'interactive-menu',
    name: 'Menu Categorizado',
    description: 'Menus colapsáveis com múltiplas categorias',
    icon: '📂',
    category: 'menu',
    json: JSON.stringify({
      ROOT: {
        type: { resolvedName: 'CanvasDropArea' },
        isCanvas: true,
        props: { bgColor: '#0f172a' },
        displayName: 'Canvas',
        custom: {},
        hidden: false,
        nodes: ['header_text', 'header_sub', 'spacer_h', 'menu_food', 'spacer_m', 'menu_services', 'spacer_b', 'menu_help'],
        linkedNodes: {},
      },
      header_text: {
        type: { resolvedName: 'TextBlock' },
        isCanvas: false,
        props: { text: '🏪 Shopping Center', fontSize: 20, fontWeight: 'bold', color: '#ffffff', textAlign: 'center', padding: 12 },
        displayName: 'Texto',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      header_sub: {
        type: { resolvedName: 'TextBlock' },
        isCanvas: false,
        props: { text: 'Toque para explorar', fontSize: 13, fontWeight: 'normal', color: 'rgba(255,255,255,0.5)', textAlign: 'center', padding: 0 },
        displayName: 'Texto',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      spacer_h: {
        type: { resolvedName: 'SpacerBlock' },
        isCanvas: false,
        props: { height: 16 },
        displayName: 'Espaçador',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      menu_food: {
        type: { resolvedName: 'MenuBlock' },
        isCanvas: false,
        props: {
          title: 'Alimentação',
          titleIcon: '🍔',
          items: [
            { id: '1', emoji: '🍕', label: 'Pizzaria', action: 'Onde fica a pizzaria?', color: '#ef4444' },
            { id: '2', emoji: '🍣', label: 'Japonês', action: 'Onde fica o restaurante japonês?', color: '#f97316' },
            { id: '3', emoji: '☕', label: 'Café', action: 'Onde fica a cafeteria?', color: '#a16207' },
            { id: '4', emoji: '🍦', label: 'Sorveteria', action: 'Onde fica a sorveteria?', color: '#ec4899' },
          ],
          layout: 'grid', columns: 2, bgColor: 'rgba(255,255,255,0.05)', bgOpacity: 1, bgBlur: 12, borderRadius: 14, gap: 6, padding: 14, titleColor: '#ffffff', titleFontSize: 13, itemBgColor: 'rgba(255,255,255,0.07)', itemTextColor: '#ffffff', itemFontSize: 12, itemBorderRadius: 10, showItemEmoji: true, collapsible: true, defaultOpen: true,
        },
        displayName: 'Menu',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      spacer_m: {
        type: { resolvedName: 'SpacerBlock' },
        isCanvas: false,
        props: { height: 8 },
        displayName: 'Espaçador',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      menu_services: {
        type: { resolvedName: 'MenuBlock' },
        isCanvas: false,
        props: {
          title: 'Serviços',
          titleIcon: '🛍️',
          items: [
            { id: '1', emoji: '👕', label: 'Moda', action: 'Lojas de moda', color: '#8b5cf6' },
            { id: '2', emoji: '💊', label: 'Farmácia', action: 'Onde fica a farmácia?', color: '#10b981' },
            { id: '3', emoji: '🎬', label: 'Cinema', action: 'Horários do cinema', color: '#3b82f6' },
          ],
          layout: 'pills', columns: 2, bgColor: 'rgba(255,255,255,0.05)', bgOpacity: 1, bgBlur: 12, borderRadius: 14, gap: 6, padding: 14, titleColor: '#ffffff', titleFontSize: 13, itemBgColor: 'rgba(255,255,255,0.07)', itemTextColor: '#ffffff', itemFontSize: 12, itemBorderRadius: 10, showItemEmoji: true, collapsible: true, defaultOpen: false,
        },
        displayName: 'Menu',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      spacer_b: {
        type: { resolvedName: 'SpacerBlock' },
        isCanvas: false,
        props: { height: 8 },
        displayName: 'Espaçador',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      menu_help: {
        type: { resolvedName: 'MenuBlock' },
        isCanvas: false,
        props: {
          title: 'Ajuda',
          titleIcon: '❓',
          items: [
            { id: '1', emoji: '📍', label: 'Mapa', action: 'Mostrar mapa do shopping', color: '#0ea5e9' },
            { id: '2', emoji: '🅿️', label: 'Estacionamento', action: 'Informações do estacionamento', color: '#64748b' },
          ],
          layout: 'list', columns: 2, bgColor: 'rgba(255,255,255,0.05)', bgOpacity: 1, bgBlur: 12, borderRadius: 14, gap: 6, padding: 14, titleColor: '#ffffff', titleFontSize: 13, itemBgColor: 'rgba(255,255,255,0.07)', itemTextColor: '#ffffff', itemFontSize: 12, itemBorderRadius: 10, showItemEmoji: true, collapsible: true, defaultOpen: false,
        },
        displayName: 'Menu',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
    }),
  },
  {
    id: 'promo-display',
    name: 'Promoções & Destaque',
    description: 'Layout promocional com imagem, badge e CTA',
    icon: '🎯',
    category: 'promo',
    json: JSON.stringify({
      ROOT: {
        type: { resolvedName: 'CanvasDropArea' },
        isCanvas: true,
        props: { bgColor: '#0f172a' },
        displayName: 'Canvas',
        custom: {},
        hidden: false,
        nodes: ['badge_promo', 'spacer_t', 'img_promo', 'text_promo', 'text_desc', 'spacer_m', 'btn_promo', 'divider_p', 'menu_promo'],
        linkedNodes: {},
      },
      badge_promo: {
        type: { resolvedName: 'BadgeBlock' },
        isCanvas: false,
        props: { text: 'OFERTA ESPECIAL', emoji: '🔥', bgColor: '#ef4444', textColor: '#ffffff', fontSize: 11, borderRadius: 999, variant: 'filled', align: 'center', pulse: true },
        displayName: 'Badge',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      spacer_t: {
        type: { resolvedName: 'SpacerBlock' },
        isCanvas: false,
        props: { height: 12 },
        displayName: 'Espaçador',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      img_promo: {
        type: { resolvedName: 'ImageBlock' },
        isCanvas: false,
        props: { src: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=400&h=250&fit=crop', alt: 'Promoção', width: '100%', height: '180px', objectFit: 'cover', borderRadius: 16, padding: 0 },
        displayName: 'Imagem',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      text_promo: {
        type: { resolvedName: 'TextBlock' },
        isCanvas: false,
        props: { text: 'Até 50% OFF', fontSize: 28, fontWeight: 'bold', color: '#ffffff', textAlign: 'center', padding: 8 },
        displayName: 'Texto',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      text_desc: {
        type: { resolvedName: 'TextBlock' },
        isCanvas: false,
        props: { text: 'Promoções exclusivas em lojas selecionadas. Válido até 28/02.', fontSize: 13, fontWeight: 'normal', color: 'rgba(255,255,255,0.6)', textAlign: 'center', padding: 4 },
        displayName: 'Texto',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      spacer_m: {
        type: { resolvedName: 'SpacerBlock' },
        isCanvas: false,
        props: { height: 12 },
        displayName: 'Espaçador',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      btn_promo: {
        type: { resolvedName: 'ButtonBlock' },
        isCanvas: false,
        props: { label: '🛒 Ver Promoções', bgColor: '#ef4444', textColor: '#ffffff', fontSize: 15, borderRadius: 12, paddingX: 24, paddingY: 14, fullWidth: true, action: 'Quais são as promoções de hoje?' },
        displayName: 'Botão',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      divider_p: {
        type: { resolvedName: 'DividerBlock' },
        isCanvas: false,
        props: { color: 'rgba(255,255,255,0.08)', thickness: 1, margin: 12, lineStyle: 'dashed' },
        displayName: 'Divisor',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      menu_promo: {
        type: { resolvedName: 'MenuBlock' },
        isCanvas: false,
        props: {
          title: 'Mais opções',
          titleIcon: '✨',
          items: [
            { id: '1', emoji: '🎁', label: 'Cupons', action: 'Mostrar cupons disponíveis', color: '#f59e0b' },
            { id: '2', emoji: '📍', label: 'Lojas', action: 'Listar lojas com desconto', color: '#8b5cf6' },
          ],
          layout: 'pills', columns: 2, bgColor: 'rgba(255,255,255,0.04)', bgOpacity: 1, bgBlur: 8, borderRadius: 14, gap: 8, padding: 14, titleColor: '#ffffff', titleFontSize: 13, itemBgColor: 'rgba(255,255,255,0.07)', itemTextColor: '#ffffff', itemFontSize: 12, itemBorderRadius: 10, showItemEmoji: true, collapsible: false, defaultOpen: true,
        },
        displayName: 'Menu',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
    }),
  },
  {
    id: 'minimal-clean',
    name: 'Minimalista',
    description: 'Layout limpo com texto e botão de ação',
    icon: '✨',
    category: 'totem',
    json: JSON.stringify({
      ROOT: {
        type: { resolvedName: 'CanvasDropArea' },
        isCanvas: true,
        props: { bgColor: '#0f172a' },
        displayName: 'Canvas',
        custom: {},
        hidden: false,
        nodes: ['spacer_top', 'icon_min', 'title_min', 'sub_min', 'spacer_mid', 'btn_min'],
        linkedNodes: {},
      },
      spacer_top: {
        type: { resolvedName: 'SpacerBlock' },
        isCanvas: false,
        props: { height: 80 },
        displayName: 'Espaçador',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      icon_min: {
        type: { resolvedName: 'IconBlock' },
        isCanvas: false,
        props: { emoji: '💎', size: 48, bgColor: 'rgba(99,102,241,0.15)', bgEnabled: true, bgSize: 88, bgBorderRadius: 24, borderColor: 'rgba(99,102,241,0.2)', borderWidth: 1, align: 'center', shadow: true },
        displayName: 'Ícone',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      title_min: {
        type: { resolvedName: 'TextBlock' },
        isCanvas: false,
        props: { text: 'Olá, como posso ajudar?', fontSize: 24, fontWeight: 'bold', color: '#ffffff', textAlign: 'center', padding: 16 },
        displayName: 'Texto',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      sub_min: {
        type: { resolvedName: 'TextBlock' },
        isCanvas: false,
        props: { text: 'Toque no botão abaixo para começar uma conversa', fontSize: 14, fontWeight: 'normal', color: 'rgba(255,255,255,0.5)', textAlign: 'center', padding: 4 },
        displayName: 'Texto',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      spacer_mid: {
        type: { resolvedName: 'SpacerBlock' },
        isCanvas: false,
        props: { height: 32 },
        displayName: 'Espaçador',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      btn_min: {
        type: { resolvedName: 'ButtonBlock' },
        isCanvas: false,
        props: { label: '💬 Iniciar Conversa', bgColor: '#6366f1', textColor: '#ffffff', fontSize: 16, borderRadius: 14, paddingX: 32, paddingY: 16, fullWidth: true, action: 'Olá!' },
        displayName: 'Botão',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
    }),
  },
  {
    id: 'full-featured',
    name: 'Completo',
    description: 'Avatar + Menu + Cards + Botões — tudo incluído',
    icon: '🚀',
    category: 'totem',
    json: JSON.stringify({
      ROOT: {
        type: { resolvedName: 'CanvasDropArea' },
        isCanvas: true,
        props: { bgColor: '#0f172a' },
        displayName: 'Canvas',
        custom: {},
        hidden: false,
        nodes: ['badge_f', 'avatar_f', 'divider_f', 'menu_f', 'spacer_f', 'card_f'],
        linkedNodes: {},
      },
      badge_f: {
        type: { resolvedName: 'BadgeBlock' },
        isCanvas: false,
        props: { text: 'Online', emoji: '🟢', bgColor: '#10b981', textColor: '#ffffff', fontSize: 11, borderRadius: 999, variant: 'glass', align: 'center', pulse: false },
        displayName: 'Badge',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      avatar_f: {
        type: { resolvedName: 'AvatarBlock' },
        isCanvas: false,
        props: { enabled: true, avatarName: 'Assistente IA', height: 220, borderRadius: 16, bgColor: 'rgba(255,255,255,0.03)' },
        displayName: 'Avatar',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      divider_f: {
        type: { resolvedName: 'DividerBlock' },
        isCanvas: false,
        props: { color: 'rgba(255,255,255,0.08)', thickness: 1, margin: 8, lineStyle: 'solid' },
        displayName: 'Divisor',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      menu_f: {
        type: { resolvedName: 'MenuBlock' },
        isCanvas: false,
        props: {
          title: 'O que deseja saber?',
          titleIcon: '🎯',
          items: [
            { id: '1', emoji: 'ℹ️', label: 'Sobre nós', action: 'Fale sobre a empresa', color: '#3b82f6' },
            { id: '2', emoji: '📍', label: 'Localização', action: 'Onde estamos?', color: '#10b981' },
            { id: '3', emoji: '🕐', label: 'Horários', action: 'Horário de funcionamento', color: '#f59e0b' },
            { id: '4', emoji: '📞', label: 'Contato', action: 'Informações de contato', color: '#ef4444' },
            { id: '5', emoji: '🎁', label: 'Promoções', action: 'Promoções disponíveis', color: '#8b5cf6' },
            { id: '6', emoji: '❓', label: 'Ajuda', action: 'Preciso de ajuda', color: '#64748b' },
          ],
          layout: 'grid', columns: 3, bgColor: 'rgba(255,255,255,0.05)', bgOpacity: 1, bgBlur: 12, borderRadius: 14, gap: 6, padding: 14, titleColor: '#ffffff', titleFontSize: 14, itemBgColor: 'rgba(255,255,255,0.07)', itemTextColor: '#ffffff', itemFontSize: 11, itemBorderRadius: 10, showItemEmoji: true, collapsible: false, defaultOpen: true,
        },
        displayName: 'Menu',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      spacer_f: {
        type: { resolvedName: 'SpacerBlock' },
        isCanvas: false,
        props: { height: 8 },
        displayName: 'Espaçador',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
      },
      card_f: {
        type: { resolvedName: 'CardBlock' },
        isCanvas: true,
        props: { title: 'Dica do dia', subtitle: '', bgColor: 'rgba(255,255,255,0.04)', bgBlur: 12, borderRadius: 14, borderColor: 'rgba(255,255,255,0.08)', padding: 16, headerIcon: '💡', showHeader: true, elevation: 'sm' },
        displayName: 'Card',
        custom: {},
        hidden: false,
        nodes: ['card_f_text'],
        linkedNodes: {},
        parent: 'ROOT',
      },
      card_f_text: {
        type: { resolvedName: 'TextBlock' },
        isCanvas: false,
        props: { text: 'Toque em qualquer opção do menu para conversar comigo!', fontSize: 12, fontWeight: 'normal', color: 'rgba(255,255,255,0.6)', textAlign: 'center', padding: 4 },
        displayName: 'Texto',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'card_f',
      },
    }),
  },
];

export const TEMPLATE_CATEGORIES = [
  { id: 'totem', label: 'Totem', icon: '📱' },
  { id: 'info', label: 'Informativo', icon: '📋' },
  { id: 'menu', label: 'Menu', icon: '📂' },
  { id: 'promo', label: 'Promoção', icon: '🎯' },
] as const;
